// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

// Read DATABASE_URL directly from process.env to avoid coupling Prisma CLI commands
// to the full Next.js runtime env schema (Resend, APP_BASE_URL, etc.).
// In CI, only REMOTE_DATABASE_URL is set; the safe-deploy script also exports it as
// DATABASE_URL when it spawns Prisma, so this fallback covers both cases.
const url = process.env.DATABASE_URL ?? process.env.REMOTE_DATABASE_URL

if (!url) {
  throw new Error(
    "Prisma config: set DATABASE_URL (local) or REMOTE_DATABASE_URL (CI/remote) before running Prisma commands.",
  )
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url,
  },
})
